services:
  cl-agent:
    build:
      context: ..
      dockerfile: cl_module_agent/Dockerfile
    image: istari-cl-agent:24.04
    platform: linux/amd64
    container_name: istari-cl-agent
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./cl_modules:/opt/local/istari_agent/istari_modules
      - istari-agent-config:/root/.config/istari_digital
      - istari-agent-data:/root/.local/share/istari_agent

  cl-agent-replica:
    build:
      context: ..
      dockerfile: cl_module_agent/Dockerfile
    image: istari-cl-agent:24.04
    platform: linux/amd64
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./cl_modules:/opt/local/istari_agent/istari_modules
    extra_hosts: ["host.docker.internal:host-gateway"]

volumes:
  istari-agent-config:
  istari-agent-data: